linters:
    disable-all: true
    enable:
    - bodyclose
    - deadcode
    - errcheck
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl
    - gochecknoglobals
    - maligned
    - prealloc

  # don't enable:
  # - godox
  # - lll
  # - dupl
  # - gocyclo
  # - gocognit
  # - scopelint
  # - depguard
  # - funlen
  # - gomnd
  # - dogsled
